
#cloud-config
# vim: syntax=yaml

output:
  all: '| tee -a /var/log/cloud-init-output.log'

write_files:
- owner: steam:steam
  path: /home/steam/headless_config.json
  permissions: '0755'
  encoding: b64
  content: {base64_headless_config}

runcmd:
  - [ systemctl, restart, systemd-journald ]
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, neos.service ]
  - [ systemctl, start, --no-block, neos.service ]
final_message: "The system is finally up, after $UPTIME seconds"
